# Generated by Django 3.2.6 on 2021-08-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='DepartmantName',
            new_name='DepartmentName',
        ),
    ]
